* 通用矩阵乘法实验报告

** 引言

*** 为什么需要矩阵乘
矩阵是线性代数的基础概念，也是现代计算机所要经常处理的数据结构之一，在诸如计算机图形学、人工智能、信息学、基础学科研究中发挥着重要作用（尤其是，在我所学的范畴内，数学建模和信号处理中尤其常用矩阵）。

在我们学校开设的“线性代数”（或高等代数）课中，我们已经在数学上认识了矩阵及其运算和性质等，但是抽象的数学描述距离真正实用地运用它为我们做实事还有一段相当的距离。所以考虑如何使用计算机储存、操作矩阵是非常具有实际意义的一件事情。

*** 矩阵在计算机的表示
我们知道，矩阵本质上仅仅是一系列数按照特定的结构（或者说顺序）排列，这很容易让我们联想到我们在 c 语言程序设计课程中学习过的数组的概念，尤其是储存数字类型的数组。这是否会为我们提供一个思路呢？让我们沿着这个想法继续思考下去，第一个问题是显而易见的——矩阵是既有行又有列的，而一般我们所讲的数组都是一维数组！

有两个巧妙的办法可以解决这个问题。比较容易理解的一个是，既然一个数组表示一组有顺序的数，而矩阵可以看作是由许多排顺序存放的数——即多个数组所组成的，是有序存放的数组，那么我们创建一个二维数组，即数组的数组是不是就可以顺利的表示一个完整的矩阵列呢？答案是肯定的，二维数组与矩阵惊人的相似之处让这一点几乎不言自明。

从朴素的角度来看，数组的“本体”是一块拥有足够多到容纳下自身内容的 *内存空间* （具体储存的位置在栈或者堆上），而我们在代码中所声明和操作的数组名则是指向这块内存首地址的 *一个指针* ，这个指针储存在栈上（如果使用 malloc 分配内存的话，其指向的内存位于堆上）。通过这个指针，外加 c 语言中支持的对指针的算术操作，就可以访问到数组中任何一个元素。

那么二维数组的一个实现思路便是，创建这样一个数组——它的内容由许多 *指向其他数组的指针* 组成，即——指向指针的指针，我们称之为二级指针。当我们想要操作矩阵中 m 行 n 列的数据时，只需要把对应二级指针的第 m 个元素取出，然后取出这个元素指向的数组的第 n 元素即可。整个过程只需要两次寻址，看起来十分便利。但是这会造成矩阵在内存中的位置碎片化等问题，也不利于内存管理。

第二种方式则是，将二维的矩阵全部储存在一维的数组里，具体的操作是，将后一行排在前一行的末尾，这样子首尾衔接，就可以在一条连续的空间中完整地储存矩阵。这其实也是 c 语言中对二维数组的处理方式。

本报告采取第二种方式。考虑到矩阵规模较大，故全部使用 malloc 函数动态分配内存。

** 实验要求

用 c 语言实现矩阵乘

输入： M 、 N 、 K 三个整数（512～2048）

问题描述：随机生成 M*N 和N*K 的两个矩阵 A,B,对这两个矩阵，做乘法得到矩阵 C。

输出：A,B,C 三个矩阵以及矩阵计算的时间。

** 实验过程

*** 朴素的定义法

依据矩阵乘法定义所实现的朴素矩阵乘法代码如下：

#+begin_src
void matrix_mul(matrix_t matrix_r,              \
                matrix_t matrix1,               \
                matrix_t matrix2,               \
                dim_t m, dim_t n, dim_t k) {
    for (dim_t i1 = 0; i1 < m; i1++) {
        for (dim_t i2 = 0; i2 < k; i2++) {
            /* malloc initliaze memory to 0 by default
             *
             * C[i1][i2] = 0
             */
            for (dim_t i3 = 0; i3 < n; i3++) {
                // C[i1][i2] += A[i1][i3] * B[i3][i2]
                matrix_r[i1 * k + i2] +=    \
                    matrix1[i1 * n + i3] *  \
                    matrix2[i3 * k + i2];
            }
        }
    }
}
#+end_src

这里只展示其算法实现部分。结果为运行十次取其平均值，如下表所示：

|    M |    N |    K | 平均时间（s） |
|------+------+------+---------------|
|  512 |  512 |  512 |      0.506073 |
| 1024 | 1024 | 1024 |      4.133914 |
| 2048 | 2048 | 2048 |     37.469813 |

